DROP TABLE IF EXISTS "estudante" CASCADE;
DROP TABLE IF EXISTS "professor" CASCADE;
DROP TABLE IF EXISTS "disciplina" CASCADE;
DROP TABLE IF EXISTS "turma" CASCADE;
DROP TABLE IF EXISTS "departamento" CASCADE;
DROP TABLE IF EXISTS "avaliacao" CASCADE;
DROP TABLE IF EXISTS "denuncia" CASCADE;