# Use uma imagem base do Node.js
FROM node:14

# Defina o diretório de trabalho dentro da imagem
WORKDIR /app

# Copie o package.json e o package-lock.json (ou yarn.lock) para a imagem
COPY package*.json ./

# Instale as dependências do projeto
RUN npm install

# Copie o código-fonte do frontend para a imagem
COPY . .

# Exponha a porta do servidor do frontend (por exemplo, 3000)
EXPOSE 3000

# Comando para iniciar o servidor do frontend
CMD ["npm", "run", "dev"]
